import core.main as spotipie
from utility.utility_spotipy import UtilitySpotiPy
from utility.json_file_generator import JsonFileGenerator

user_auth_token = "BQAyGeLGvzM714AjRCcX6maYSii_fw6mCG64iutNmG2spDsvYrescYHHYWABGBb-dLlykHuqNJPZjPexNNxCyatRZEXJac8kv89DYCea-hrrq24zNLdPY4D6tcPQxk0ktvW3okVrAVXaRT7jH5FVDX3mVL6Oj6o0PLCMr3bHLlHK4Y-mZVNK4IdabEQlx8zLqZJkFJwaiHBkhvEQ&token_type=Bearer&expires_in=3600&state=yhtdfciprfv"

top10_artists = spotipie.get_my_top_artists(token=user_auth_token, term="long_term")
file = JsonFileGenerator(items=top10_artists)
file.json_generator()
